### ISSUE TITLE
[DOCS] Lack of documentation. why ?

### ISSUE THREAD

**Issue by ErrorxCode** [m3o/m3o#193]
### Description

I believe that m3o has a great cloud service for building applications. But the problem is developers don't know how to use that services. There is no proper documentation for the cloud services such as **Functions** and **Apps**. I request the developer to please put interest in this issue of documentation and make it better than always.
,

**Comment by asim** [comment]
Can you please specify what documentation you need and where you expect it to be. It's really easy for us to write stuff but it may not be useful.

**Comment by asim** [comment]
See google cloud functions https://cloud.google.com/functions/docs/first-java

We're not in a position to write docs for this stuff right now. The reason being because we're still iterating on the experience. Writing docs would imply its finished, it's not. We don't want to emulate an existing cloud experience. Given its alpha/beta nature, I'd just suggest to go try use something else. We don't want to convince you to use it and we're not going to be able to support your usage of it right now.

**Comment by ErrorxCode** [comment]
It's okay. BTW, that link was enough for documentation of **Functions**. Thanks for the link.
